// รายการคำศัพท์ตัวอย่าง พร้อมหมวดหมู่และฟุริกานะ (ถ้ามี)
window.vocabData = [
    // ชีวิตประจำวัน
    { jp: 'ありがとう', romaji: 'arigatou', th: 'ขอบคุณ', cat: 'ชีวิตประจำวัน' },
    { jp: 'おはよう', romaji: 'ohayou', th: 'สวัสดี (ตอนเช้า)', cat: 'ชีวิตประจำวัน' },
    { jp: 'こんにちは', romaji: 'konnichiwa', th: 'สวัสดี (ตอนกลางวัน)', cat: 'ชีวิตประจำวัน' },
    { jp: 'こんばんは', romaji: 'konbanwa', th: 'สวัสดี (ตอนเย็น)', cat: 'ชีวิตประจำวัน' },
    { jp: 'さようなら', romaji: 'sayounara', th: 'ลาก่อน', cat: 'ชีวิตประจำวัน' },
    { jp: 'すみません', romaji: 'sumimasen', th: ['ขอโทษ', 'ขออภัย'], cat: 'ชีวิตประจำวัน' },
    { jp: 'はい', romaji: 'hai', th: 'ใช่', cat: 'ชีวิตประจำวัน' },
    { jp: 'いいえ', romaji: 'iie', th: 'ไม่ใช่', cat: 'ชีวิตประจำวัน' },
    { jp: 'お願いします', romaji: 'onegaishimasu', th: ['ขอร้อง', 'กรุณา'], cat: 'ชีวิตประจำวัน', furigana: 'おねがいします' },
    { jp: '元気', romaji: 'genki', th: 'สบายดี', cat: 'ชีวิตประจำวัน', furigana: 'げんき' },
    { jp: 'わかります', romaji: 'wakarimasu', th: 'เข้าใจ', cat: 'ชีวิตประจำวัน' },
    { jp: 'あります', romaji: 'arimasu', th: ['มี', 'มี (ใช้กับสิ่งไม่มีชีวิต)'], cat: 'ชีวิตประจำวัน' },
    { jp: 'すき', romaji: 'suki', th: 'ชอบ', cat: 'ชีวิตประจำวัน', furigana: 'すき' },
    { jp: 'きらい', romaji: 'kirai', th: 'เกลียด', cat: 'ชีวิตประจำวัน', furigana: 'きらい' },
    { jp: 'じょうず', romaji: 'jouzu', th: ['เก่ง', 'เก่ง (ชำนาญ)'], cat: 'ชีวิตประจำวัน', furigana: 'じょうず' },
    { jp: 'へた', romaji: 'heta', th: ['ไม่เก่ง', 'ไม่เก่ง (ไม่ชำนาญ)'], cat: 'ชีวิตประจำวัน', furigana: 'へた' },
    { jp: 'ぜんぜん', romaji: 'zenzen', th: ['ไม่เลย', 'ไม่เลย (ใช้กับรูปปฏิเสธ)'], cat: 'ชีวิตประจำวัน', furigana: 'ぜんぜん' },
    { jp: 'はやく', romaji: 'hayaku', th: 'เร็ว ๆ', cat: 'ชีวิตประจำวัน', furigana: 'はやく' },
    { jp: 'から', romaji: 'kara', th: 'เพราะว่า～', cat: 'ชีวิตประจำวัน' },
    { jp: 'どうして', romaji: 'doushite', th: 'ทำไม', cat: 'ชีวิตประจำวัน', furigana: 'どうして' },
    { jp: 'いっしょに いかがですか', romaji: 'issho ni ikaga desu ka', th: 'ไปด้วยกันไหม', cat: 'ชีวิตประจำวัน', furigana: 'いっしょに いかがですか' },
    { jp: 'は ちょっと…', romaji: 'wa chotto...', th: ['ไม่ค่อยสะดวก', 'ไม่ค่อยสะดวกน่ะครับ/ค่ะ'], cat: 'ชีวิตประจำวัน' },
    { jp: 'また こんど おねがいします', romaji: 'mata kondo onegaishimasu', th: ['เอาไว้คราวหน้า', 'เอาไว้คราวหน้านะครับ/ค่ะ'], cat: 'ชีวิตประจำวัน', furigana: 'また こんど おねがいします' },
    { jp: 'じかん', romaji: 'jikan', th: 'เวลา', cat: 'ชีวิตประจำวัน', furigana: 'じかん' },
    { jp: 'ようじ', romaji: 'youji', th: 'ธุระ', cat: 'ชีวิตประจำวัน', furigana: 'ようじ' },
    { jp: 'やくそく', romaji: 'yakusoku', th: ['การนัดหมาย', 'สัญญา'], cat: 'ชีวิตประจำวัน', furigana: 'やくそく' },
    { jp: 'アルバイト', romaji: 'arubaito', th: ['งานพิเศษ', 'Part-time'], cat: 'ชีวิตประจำวัน' },
    // อาหาร
    { jp: 'ごはん', romaji: 'gohan', th: 'ข้าว', cat: 'อาหาร' },
    { jp: 'みず', romaji: 'mizu', th: 'น้ำ', cat: 'อาหาร' },
    { jp: 'さかな', romaji: 'sakana', th: 'ปลา', cat: 'อาหาร' },
    { jp: 'にく', romaji: 'niku', th: 'เนื้อสัตว์', cat: 'อาหาร' },
    { jp: 'やさい', romaji: 'yasai', th: 'ผัก', cat: 'อาหาร' },
    { jp: 'くだもの', romaji: 'kudamono', th: 'ผลไม้', cat: 'อาหาร' },
    { jp: 'たまご', romaji: 'tamago', th: 'ไข่', cat: 'อาหาร' },
    { jp: 'パン', romaji: 'pan', th: 'ขนมปัง', cat: 'อาหาร' },
    { jp: 'ミルク', romaji: 'miruku', th: 'นม', cat: 'อาหาร' },
    { jp: 'ジュース', romaji: 'juusu', th: 'น้ำผลไม้', cat: 'อาหาร' },
    { jp: 'のみもの', romaji: 'nomimono', th: 'เครื่องดื่ม', cat: 'อาหาร', furigana: 'のみもの' },
    { jp: 'りょうり', romaji: 'ryouri', th: 'อาหาร, การทำอาหาร', cat: 'อาหาร', furigana: 'りょうり' },
    // กีฬา
    { jp: 'サッカー', romaji: 'sakka-', th: 'ฟุตบอล', cat: 'กีฬา' },
    { jp: 'やきゅう', romaji: 'yakyuu', th: 'เบสบอล', cat: 'กีฬา' },
    { jp: 'テニス', romaji: 'tenisu', th: 'เทนนิส', cat: 'กีฬา' },
    { jp: 'スポーツ', romaji: 'supootsu', th: 'กีฬา', cat: 'กีฬา' },
    { jp: 'ダンス', romaji: 'dansu', th: 'เต้นรำ', cat: 'กีฬา' },
    // ดนตรี
    { jp: 'おんがく', romaji: 'ongaku', th: 'ดนตรี', cat: 'ดนตรี', furigana: 'おんがく' },
    { jp: 'うた', romaji: 'uta', th: 'เพลง', cat: 'ดนตรี', furigana: 'うた' },
    { jp: 'クラシック', romaji: 'kurashikku', th: 'เพลงคลาสสิก', cat: 'ดนตรี' },
    { jp: 'ジャズ', romaji: 'jazu', th: 'แจ๊ส', cat: 'ดนตรี' },
    { jp: 'コンサート', romaji: 'konsaato', th: 'คอนเสิร์ต', cat: 'ดนตรี' },
    { jp: 'カラオケ', romaji: 'karaoke', th: 'คาราโอเกะ', cat: 'ดนตรี' },
    // ศิลปะ
    { jp: 'かぶき', romaji: 'kabuki', th: ['คาบุกิ', 'คาบุกิ (ละครเพลงญี่ปุ่น)'], cat: 'ศิลปะ', furigana: 'かぶき' },
    { jp: 'え', romaji: 'e', th: 'รูปวาด, ภาพวาด', cat: 'ศิลปะ', furigana: 'え' },
    { jp: 'じ', romaji: 'ji', th: 'ตัวอักษร', cat: 'ศิลปะ', furigana: 'じ' },
    { jp: 'かんじ', romaji: 'kanji', th: 'อักษรคันจิ', cat: 'ศิลปะ', furigana: 'かんじ' },
    { jp: 'ひらがな', romaji: 'hiragana', th: 'อักษรฮิระงะนะ', cat: 'ศิลปะ' },
    { jp: 'かたかな', romaji: 'katakana', th: 'อักษรคะตะกะนะ', cat: 'ศิลปะ' },
    { jp: 'ローマじ', romaji: 'roomaji', th: 'อักษรโรมัน', cat: 'ศิลปะ', furigana: 'ローマじ' },
    // ครอบครัว
    { jp: 'ちち', romaji: 'chichi', th: 'พ่อ', cat: 'ครอบครัว' },
    { jp: 'はは', romaji: 'haha', th: 'แม่', cat: 'ครอบครัว' },
    { jp: 'あに', romaji: 'ani', th: 'พี่ชาย', cat: 'ครอบครัว' },
    { jp: 'あね', romaji: 'ane', th: 'พี่สาว', cat: 'ครอบครัว' },
    { jp: 'おとうと', romaji: 'otouto', th: 'น้องชาย', cat: 'ครอบครัว' },
    { jp: 'いもうと', romaji: 'imouto', th: 'น้องสาว', cat: 'ครอบครัว' },
    { jp: 'そふ', romaji: 'sofu', th: ['ปู่', 'ตา'], cat: 'ครอบครัว' },
    { jp: 'そぼ', romaji: 'sobo', th: ['ย่า', 'ยาย'], cat: 'ครอบครัว' },
    { jp: 'ごしゅじん', romaji: 'goshujin', th: ['สามี', 'สามี (ของคนอื่น)'], cat: 'ครอบครัว', furigana: 'ごしゅじん' },
    { jp: 'おっと', romaji: 'otto', th: ['สามี', 'สามี (ของตัวเอง)'], cat: 'ครอบครัว', furigana: 'おっと' },
    { jp: 'ごしゅふ', romaji: 'goshufu', th: 'เจ้าของบ้าน', cat: 'ครอบครัว', furigana: 'ごしゅふ' },
    { jp: 'おくさん', romaji: 'okusan', th: ['ภรรยา', 'ภรรยา (ของคนอื่น)'], cat: 'ครอบครัว', furigana: 'おくさん' },
    { jp: 'つま', romaji: 'tsuma', th: ['ภรรยา', 'ภรรยา (ของตัวเอง)'], cat: 'ครอบครัว', furigana: 'つま' },
    { jp: 'かない', romaji: 'kanai', th: ['ภรรยา', 'ภรรยา (ของตัวเอง)'], cat: 'ครอบครัว', furigana: 'かない' },
    { jp: 'こども', romaji: 'kodomo', th: 'ลูก', cat: 'ครอบครัว', furigana: 'こども' },
    // การเดินทาง
    { jp: 'でんしゃ', romaji: 'densha', th: 'รถไฟ', cat: 'การเดินทาง', furigana: 'でんしゃ' },
    { jp: 'くるま', romaji: 'kuruma', th: 'รถยนต์', cat: 'การเดินทาง' },
    { jp: 'バス', romaji: 'basu', th: 'รถบัส', cat: 'การเดินทาง' },
    { jp: 'ひこうき', romaji: 'hikouki', th: 'เครื่องบิน', cat: 'การเดินทาง' },
    { jp: 'ちかてつ', romaji: 'chikatetsu', th: 'รถไฟใต้ดิน', cat: 'การเดินทาง' },
    { jp: 'タクシー', romaji: 'takushii', th: 'แท็กซี่', cat: 'การเดินทาง' },
    { jp: 'じてんしゃ', romaji: 'jitensha', th: 'จักรยาน', cat: 'การเดินทาง' },
    { jp: 'あるく', romaji: 'aruku', th: 'เดิน', cat: 'การเดินทาง' },
    { jp: 'りょこう', romaji: 'ryokou', th: 'การท่องเที่ยว', cat: 'การเดินทาง', furigana: 'りょこう' },
    // สถานที่
    { jp: 'がっこう', romaji: 'gakkou', th: 'โรงเรียน', cat: 'สถานที่' },
    { jp: 'いえ', romaji: 'ie', th: 'บ้าน', cat: 'สถานที่' },
    { jp: 'みせ', romaji: 'mise', th: 'ร้านค้า', cat: 'สถานที่' },
    { jp: 'えき', romaji: 'eki', th: 'สถานีรถไฟ', cat: 'สถานที่' },
    { jp: 'びょういん', romaji: 'byouin', th: 'โรงพยาบาล', cat: 'สถานที่', furigana: 'びょういん' },
    { jp: 'こうえん', romaji: 'kouen', th: 'สวนสาธารณะ', cat: 'สถานที่' },
    { jp: 'ゆうびんきょく', romaji: 'yuubinkyoku', th: 'ไปรษณีย์', cat: 'สถานที่' },
    // ตัวเลข
    { jp: 'いち', romaji: 'ichi', th: 'หนึ่ง', cat: 'ตัวเลข' },
    { jp: 'に', romaji: 'ni', th: 'สอง', cat: 'ตัวเลข' },
    { jp: 'さん', romaji: 'san', th: 'สาม', cat: 'ตัวเลข' },
    { jp: 'し/よん', romaji: 'shi/yon', th: 'สี่', cat: 'ตัวเลข' },
    { jp: 'ご', romaji: 'go', th: 'ห้า', cat: 'ตัวเลข' },
    { jp: 'ろく', romaji: 'roku', th: 'หก', cat: 'ตัวเลข' },
    { jp: 'しち/なな', romaji: 'shichi/nana', th: 'เจ็ด', cat: 'ตัวเลข' },
    { jp: 'はち', romaji: 'hachi', th: 'แปด', cat: 'ตัวเลข' },
    { jp: 'きゅう', romaji: 'kyuu', th: 'เก้า', cat: 'ตัวเลข' },
    { jp: 'じゅう', romaji: 'juu', th: 'สิบ', cat: 'ตัวเลข' },
    // สี
    { jp: 'あか', romaji: 'aka', th: 'สีแดง', cat: 'สี' },
    { jp: 'あお', romaji: 'ao', th: 'สีน้ำเงิน', cat: 'สี' },
    { jp: 'きいろ', romaji: 'kiiro', th: 'สีเหลือง', cat: 'สี' },
    { jp: 'みどり', romaji: 'midori', th: 'สีเขียว', cat: 'สี' },
    { jp: 'しろ', romaji: 'shiro', th: 'สีขาว', cat: 'สี' },
    { jp: 'くろ', romaji: 'kuro', th: 'สีดำ', cat: 'สี' },
    // อารมณ์
    { jp: 'うれしい', romaji: 'ureshii', th: 'ดีใจ', cat: 'อารมณ์' },
    { jp: 'かなしい', romaji: 'kanashii', th: 'เศร้า', cat: 'อารมณ์' },
    { jp: 'たのしい', romaji: 'tanoshii', th: 'สนุก', cat: 'อารมณ์' },
    { jp: 'こわい', romaji: 'kowai', th: 'กลัว', cat: 'อารมณ์' },
    { jp: 'おこる', romaji: 'okoru', th: 'โกรธ', cat: 'อารมณ์' },
    // สัตว์
    { jp: 'いぬ', romaji: 'inu', th: 'สุนัข', cat: 'สัตว์' },
    { jp: 'ねこ', romaji: 'neko', th: 'แมว', cat: 'สัตว์' },
    { jp: 'とり', romaji: 'tori', th: 'นก', cat: 'สัตว์' },
    { jp: 'さかな', romaji: 'sakana', th: 'ปลา', cat: 'สัตว์' },
    { jp: 'うま', romaji: 'uma', th: 'ม้า', cat: 'สัตว์' },
    { jp: 'うし', romaji: 'ushi', th: 'วัว', cat: 'สัตว์' },
    // ฤดูกาล
    { jp: 'はる', romaji: 'haru', th: 'ฤดูใบไม้ผลิ', cat: 'ฤดูกาล' },
    { jp: 'なつ', romaji: 'natsu', th: 'ฤดูร้อน', cat: 'ฤดูกาล' },
    { jp: 'あき', romaji: 'aki', th: 'ฤดูใบไม้ร่วง', cat: 'ฤดูกาล' },
    { jp: 'ふゆ', romaji: 'fuyu', th: 'ฤดูหนาว', cat: 'ฤดูกาล' },
    // เทคโนโลยี
    { jp: 'パソコン', romaji: 'pasokon', th: 'คอมพิวเตอร์', cat: 'เทคโนโลยี' },
    { jp: 'スマホ', romaji: 'sumaho', th: 'สมาร์ทโฟน', cat: 'เทคโนโลยี' },
    { jp: 'インターネット', romaji: 'inta-netto', th: 'อินเทอร์เน็ต', cat: 'เทคโนโลยี' },
    // อาชีพ
    { jp: 'いしゃ', romaji: 'isha', th: 'หมอ', cat: 'อาชีพ' },
    { jp: 'せんせい', romaji: 'sensei', th: 'ครู', cat: 'อาชีพ' },
    { jp: 'がくせい', romaji: 'gakusei', th: 'นักเรียน', cat: 'อาชีพ' },
    { jp: 'かいしゃいん', romaji: 'kaishain', th: 'พนักงานบริษัท', cat: 'อาชีพ' },
    { jp: 'こうむいん', romaji: 'koumuin', th: 'ข้าราชการ', cat: 'อาชีพ' },
    { jp: 'エンジニア', romaji: 'enjinia', th: 'วิศวกร', cat: 'อาชีพ' },
    { jp: 'けいさつかん', romaji: 'keisatsukan', th: 'ตำรวจ', cat: 'อาชีพ' },
    // เครื่องใช้ในบ้าน
    { jp: 'でんき', romaji: 'denki', th: 'ไฟฟ้า', cat: 'เครื่องใช้ในบ้าน' },
    { jp: 'エアコン', romaji: 'eakon', th: 'แอร์', cat: 'เครื่องใช้ในบ้าน' },
    { jp: 'れいぞうこ', romaji: 'reizouko', th: 'ตู้เย็น', cat: 'เครื่องใช้ในบ้าน' },
    { jp: 'せんたくき', romaji: 'sentakuki', th: 'เครื่องซักผ้า', cat: 'เครื่องใช้ในบ้าน' },
    { jp: 'そうじき', romaji: 'soujiki', th: 'เครื่องดูดฝุ่น', cat: 'เครื่องใช้ในบ้าน' },
    { jp: 'でんわ', romaji: 'denwa', th: 'โทรศัพท์', cat: 'เครื่องใช้ในบ้าน' },
    // ร่างกาย
    { jp: 'あたま', romaji: 'atama', th: 'หัว', cat: 'ร่างกาย' },
    { jp: 'め', romaji: 'me', th: 'ตา', cat: 'ร่างกาย' },
    { jp: 'みみ', romaji: 'mimi', th: 'หู', cat: 'ร่างกาย' },
    { jp: 'くち', romaji: 'kuchi', th: 'ปาก', cat: 'ร่างกาย' },
    { jp: 'て', romaji: 'te', th: 'มือ', cat: 'ร่างกาย' },
    { jp: 'あし', romaji: 'ashi', th: 'ขา/เท้า', cat: 'ร่างกาย' },
    // วันในสัปดาห์
    { jp: 'げつようび', romaji: 'getsuyoubi', th: 'วันจันทร์', cat: 'วันในสัปดาห์' },
    { jp: 'かようび', romaji: 'kayoubi', th: 'วันอังคาร', cat: 'วันในสัปดาห์' },
    { jp: 'すいようび', romaji: 'suiyoubi', th: 'วันพุธ', cat: 'วันในสัปดาห์' },
    { jp: 'もくようび', romaji: 'mokuyoubi', th: 'วันพฤหัสบดี', cat: 'วันในสัปดาห์' },
    { jp: 'きんようび', romaji: 'kinyoubi', th: 'วันศุกร์', cat: 'วันในสัปดาห์' },
    { jp: 'どようび', romaji: 'doyoubi', th: 'วันเสาร์', cat: 'วันในสัปดาห์' },
    { jp: 'にちようび', romaji: 'nichiyoubi', th: 'วันอาทิตย์', cat: 'วันในสัปดาห์' },
    // เดือน
    { jp: 'いちがつ', romaji: 'ichigatsu', th: 'มกราคม', cat: 'เดือน' },
    { jp: 'にがつ', romaji: 'nigatsu', th: 'กุมภาพันธ์', cat: 'เดือน' },
    { jp: 'さんがつ', romaji: 'sangatsu', th: 'มีนาคม', cat: 'เดือน' },
    { jp: 'しがつ', romaji: 'shigatsu', th: 'เมษายน', cat: 'เดือน' },
    { jp: 'ごがつ', romaji: 'gogatsu', th: 'พฤษภาคม', cat: 'เดือน' },
    { jp: 'ろくがつ', romaji: 'rokugatsu', th: 'มิถุนายน', cat: 'เดือน' },
    { jp: 'しちがつ', romaji: 'shichigatsu', th: 'กรกฎาคม', cat: 'เดือน' },
    { jp: 'はちがつ', romaji: 'hachigatsu', th: 'สิงหาคม', cat: 'เดือน' },
    { jp: 'くがつ', romaji: 'kugatsu', th: 'กันยายน', cat: 'เดือน' },
    { jp: 'じゅうがつ', romaji: 'juugatsu', th: 'ตุลาคม', cat: 'เดือน' },
    { jp: 'じゅういちがつ', romaji: 'juuichigatsu', th: 'พฤศจิกายน', cat: 'เดือน' },
    { jp: 'じゅうにがつ', romaji: 'juunigatsu', th: 'ธันวาคม', cat: 'เดือน' },
    // ธรรมชาติ
    { jp: 'やま', romaji: 'yama', th: 'ภูเขา', cat: 'ธรรมชาติ' },
    { jp: 'かわ', romaji: 'kawa', th: 'แม่น้ำ', cat: 'ธรรมชาติ' },
    { jp: 'うみ', romaji: 'umi', th: 'ทะเล', cat: 'ธรรมชาติ' },
    { jp: 'もり', romaji: 'mori', th: 'ป่า', cat: 'ธรรมชาติ' },
    { jp: 'そら', romaji: 'sora', th: 'ท้องฟ้า', cat: 'ธรรมชาติ' },
    { jp: 'たいよう', romaji: 'taiyou', th: 'พระอาทิตย์', cat: 'ธรรมชาติ' },
    { jp: 'つき', romaji: 'tsuki', th: 'พระจันทร์', cat: 'ธรรมชาติ' },
    // เครื่องแต่งกาย
    { jp: 'シャツ', romaji: 'shatsu', th: 'เสื้อเชิ้ต', cat: 'เครื่องแต่งกาย' },
    { jp: 'ズボン', romaji: 'zubon', th: 'กางเกง', cat: 'เครื่องแต่งกาย' },
    { jp: 'スカート', romaji: 'sukaato', th: 'กระโปรง', cat: 'เครื่องแต่งกาย' },
    { jp: 'くつ', romaji: 'kutsu', th: 'รองเท้า', cat: 'เครื่องแต่งกาย' },
    { jp: 'ぼうし', romaji: 'boushi', th: 'หมวก', cat: 'เครื่องแต่งกาย' },
    // เครื่องเขียน
    { jp: 'えんぴつ', romaji: 'enpitsu', th: 'ดินสอ', cat: 'เครื่องเขียน' },
    { jp: 'ペン', romaji: 'pen', th: 'ปากกา', cat: 'เครื่องเขียน' },
    { jp: 'けしごむ', romaji: 'keshigomu', th: 'ยางลบ', cat: 'เครื่องเขียน' },
    { jp: 'ノート', romaji: 'nooto', th: 'สมุด', cat: 'เครื่องเขียน' },
    { jp: 'ほん', romaji: 'hon', th: 'หนังสือ', cat: 'เครื่องเขียน' },
    // เทศกาล
    { jp: 'おしょうがつ', romaji: 'oshougatsu', th: 'ปีใหม่', cat: 'เทศกาล' },
    { jp: 'たなばた', romaji: 'tanabata', th: 'เทศกาลทานาบาตะ', cat: 'เทศกาล' },
    { jp: 'はなみ', romaji: 'hanami', th: 'ชมดอกซากุระ', cat: 'เทศกาล' },
    { jp: 'おぼん', romaji: 'obon', th: 'เทศกาลโอบ้ง', cat: 'เทศกาล' },
    { jp: 'クリスマス', romaji: 'kurisumasu', th: 'คริสต์มาส', cat: 'เทศกาล' }
];
